# Generated by Django 5.0.2 on 2024-03-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_placedesc_locationdatabase_place_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdatabase',
            old_name='tag',
            new_name='tags',
        ),
    ]
