# Generated by Django 5.0.2 on 2024-03-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_userdatabase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdatabase',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userdatabase',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdatabase',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
