# Generated by Django 5.0.3 on 2024-03-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_userdatabase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='jobs',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
