# Generated by Django 5.0.3 on 2024-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_userdatabase_jobs_alter_userdatabase_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='username',
            field=models.CharField(default='a_user', max_length=50),
        ),
    ]
