# Generated by Django 5.0.3 on 2024-03-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_userdatabase_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
