# Generated by Django 5.0.3 on 2024-04-22 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_userdatabase_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlocationlogging',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clicked_date', models.DateTimeField(auto_now_add=True)),
                ('clicked_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.locationdatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usersearchlogging',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('search_query', models.TextField()),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
