# Generated by Django 5.0.3 on 2024-04-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_locationdatabase_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdatabase',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
