# Generated by Django 5.0.2 on 2024-05-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_locationdatabase_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdatabase',
            name='place_desc',
            field=models.CharField(max_length=500),
        ),
    ]
