# Generated by Django 5.0.2 on 2024-05-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_usersearchlogging_result_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdatabase',
            name='place_desc',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='locationdatabase',
            name='place_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
