# Generated by Django 5.0.2 on 2024-05-08 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_locationdatabase_place_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdatabase',
            name='address',
            field=models.CharField(default='Quy Nhon', max_length=100),
        ),
        migrations.AlterField(
            model_name='locationdatabase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='locationdatabase',
            name='ratings',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
