# Generated by Django 5.0.2 on 2024-05-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_locationdatabase_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersearchlogging',
            old_name='user',
            new_name='username',
        ),
    ]
