# Generated by Django 5.0.2 on 2024-05-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_rename_user_usersearchlogging_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchlogging',
            name='username',
            field=models.TextField(),
        ),
    ]
