# Generated by Django 5.0.2 on 2024-05-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_userlocationlogging_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdatabase',
            name='tags',
            field=models.CharField(max_length=200),
        ),
    ]
