# Generated by Django 5.0.2 on 2024-08-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_userratinglogging'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdatabase',
            name='suitable_weather',
            field=models.JSONField(default=list),
        ),
    ]
