# Generated by Django 5.0.2 on 2024-08-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_locationdatabase_suitable_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdatabase',
            name='suitable_weather',
            field=models.JSONField(default=['any']),
        ),
    ]
