# Generated by Django 5.0.2 on 2024-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_alter_locationdatabase_suitable_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdatabase',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlocationlogging',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
