# Generated by Django 4.2.15 on 2024-08-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_usertagweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdatabase',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
