# Generated by Django 4.2.15 on 2024-08-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_alter_locationdatabase_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='username',
            field=models.CharField(default='default_username', max_length=50),
        ),
    ]
