# Generated by Django 4.2.15 on 2024-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_alter_userdatabase_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='weights_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
