# Generated by Django 4.2.15 on 2024-08-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_userdatabase_weights_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchlogging',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
