# Generated by Django 4.2.15 on 2024-08-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_usersearchlogging_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='weatherdatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('weather_text', models.CharField(max_length=255)),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
