# Generated by Django 4.2.15 on 2024-08-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_weatherdatabase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdatabase',
            old_name='humidity',
            new_name='avg_humidity',
        ),
        migrations.AddField(
            model_name='weatherdatabase',
            name='max_humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherdatabase',
            name='min_humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
