# Generated by Django 4.2.15 on 2024-08-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_rename_humidity_weatherdatabase_avg_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdatabase',
            name='avg_humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdatabase',
            name='max_humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdatabase',
            name='max_temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdatabase',
            name='min_humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdatabase',
            name='min_temperature',
            field=models.FloatField(default=0),
        ),
    ]
